---
output:
  pdf_document: default
  html_document:
    df_print: paged
---


### Sequence Name:
```{r,echo = FALSE,comment=NA }
writeLines(i)
```

### Mature/5p sequence:
```{r,echo = FALSE,comment=NA }
writeLines(as.character(toprintaligns[toprintaligns$ID == i,]$`5p arm`))
```

### Star/3p sequence:
```{r,echo = FALSE,comment=NA }
writeLines(as.character(toprintaligns[toprintaligns$ID == i,]$`3p arm`))
```

### Genomic coordinates:
```{r,echo = FALSE,comment=NA }
writeLines(as.character(toreturnall[toprintaligns$ID == i,]$Loci))
```

### Which arm is mature arm:
```{r,echo = FALSE,comment=NA }
writeLines(as.character(toreturnall[toprintaligns$ID == i,]$whoismature))
```
### Final score:
```{r,echo = FALSE,comment=NA }
writeLines(as.character(toreturnall[toprintaligns$ID == i,]$Score))
```
### Structure plot:
```{r,echo = FALSE,comment=NA }
library("jpeg")
im <- readJPEG(paste0('./www/images/', i, "_fold.jpg"))
plot (0:1, 0:1, type = "n", ann = FALSE, axes = FALSE)
rasterImage (im, 0, 0, 1, 1)
```

### Expression plot:
```{r,echo = FALSE,comment=NA }
library("png")
png <- readPNG(paste0('./www/plots/', i, ".png"))
plot.new()
rasterImage(png, 0, 0, 1, 1)
```
